In [20]:
import pandas as pd

# Cargar el dataset combinado
df_assessment_combined = pd.read_csv('Assessment_combinado.csv')
Courses_combined = pd.read_csv('Courses_combinado.csv')
Registration_combined = pd.read_csv('Registration_combinado.csv')
StudentAssessment_combined = pd.read_csv('StudentAssessment_combinado.csv')
StudentInfo_combined = pd.read_csv('StudentInfo_combinado.csv')
StudentVle_combined = pd.read_csv('StudentVle_combinado.csv')
vle_combined = pd.read_csv('Vle_combinado.csv')

# Revisar estructura
print(df_assessment_combined.head())
print(Courses_combined.head())
print(Registration_combined.head())
print(StudentAssessment_combined.head())
print(StudentInfo_combined.head())
print(StudentVle_combined.head())
print(vle_combined.head())

/tmp/ipython-input-20-2947198348.py:7: DtypeWarning: Columns (2,5,6,8,9,10,11,13,15,16,17,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  StudentAssessment_combined = pd.read_csv('StudentAssessment_combinado.csv')
/tmp/ipython-input-20-2947198348.py:9: DtypeWarning: Columns (6,7,9,10,11,12,13,14,15,19) have mixed types. Specify dtype option on import or set low_memory=False.
  StudentVle_combined = pd.read_csv('StudentVle_combinado.csv')

  code_module code_presentation  id_assessment assessment_type   date  weight  \
0         AAA             2013J         1752.0             TMA   19.0    10.0
1         AAA             2013J         1753.0             TMA   54.0    20.0
2         AAA             2013J         1754.0             TMA  117.0    20.0
3         AAA             2013J         1755.0             TMA  166.0    20.0
4         AAA             2013J         1756.0             TMA  215.0    30.0

  id_assessment_general    source guid_assess_id  days
0                  1752  original            NaN   NaN
1                  1753  original            NaN   NaN
2                  1754  original            NaN   NaN
3                  1755  original            NaN   NaN
4                  1756  original            NaN   NaN
  code_module code_presentation  module_presentation_length    source
0         AAA             2013J                         268  original
1         AAA             2014J                         269  original
2         BBB             2013J                         268  original
3         BBB             2014J                         262  original
4         BBB             2013B                         240  original
  code_module code_presentation  id_student  date_registration  \
0         AAA             2013J     11391.0             -159.0
1         AAA             2013J     28400.0              -53.0
2         AAA             2013J     30268.0              -92.0
3         AAA             2013J     31604.0              -52.0
4         AAA             2013J     32885.0             -176.0

   date_unregistration student_id_general    source guid_studente_id
0                  NaN              11391  original              NaN
1                  NaN              28400  original              NaN
2                 12.0              30268  original              NaN
3                  NaN              31604  original              NaN
4                  NaN              32885  original              NaN
   id_assessment  id_student date_submitted  is_banked  score  \
0         1752.0     11391.0             18          0   78.0
1         1752.0     28400.0             22          0   70.0
2         1752.0     31604.0             17          0   72.0
3         1752.0     32885.0             26          0   69.0
4         1752.0     38053.0             19          0   79.0

  student_id_general id_assessment_general    source guid_student_id  \
0              11391                  1752  original             NaN
1              28400                  1752  original             NaN
2              31604                  1752  original             NaN
3              32885                  1752  original             NaN
4              38053                  1752  original             NaN

  guid_assess_id  ... age_band num_of_prev_attempts  studied_credits  \
0            NaN  ...      NaN                  NaN              NaN
1            NaN  ...      NaN                  NaN              NaN
2            NaN  ...      NaN                  NaN              NaN
3            NaN  ...      NaN                  NaN              NaN
4            NaN  ...      NaN                  NaN              NaN

  disability  final_result status module presentation  date_real_days  \
0        NaN           NaN    NaN    NaN          NaN             NaN
1        NaN           NaN    NaN    NaN          NaN             NaN
2        NaN           NaN    NaN    NaN          NaN             NaN
3        NaN           NaN    NaN    NaN          NaN             NaN
4        NaN           NaN    NaN    NaN          NaN             NaN

   id_assetcode
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN

[5 rows x 27 columns]
  code_module code_presentation  id_student gender                region  \
0         AAA             2013J     11391.0      M   East Anglian Region
1         AAA             2013J     28400.0      F              Scotland
2         AAA             2013J     30268.0      F  North Western Region
3         AAA             2013J     31604.0      F     South East Region
4         AAA             2013J     32885.0      F  West Midlands Region

       highest_education imd_band age_band  num_of_prev_attempts  \
0       HE Qualification  90-100%     55<=                   0.0
1       HE Qualification   20-30%    35-55                   0.0
2  A Level or Equivalent   30-40%    35-55                   0.0
3  A Level or Equivalent   50-60%    35-55                   0.0
4     Lower Than A Level   50-60%     0-35                   0.0

   studied_credits disability final_result student_id_general    source  \
0            240.0          N         Pass              11391  original
1             60.0          N         Pass              28400  original
2             60.0          Y    Withdrawn              30268  original
3             60.0          N         Pass              31604  original
4             60.0          N         Pass              32885  original

  guid_student_id
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
  code_module code_presentation  id_student   id_site  date  sum_click  \
0         AAA             2013J     28400.0  546652.0 -10.0        4.0
1         AAA             2013J     28400.0  546652.0 -10.0        1.0
2         AAA             2013J     28400.0  546614.0 -10.0       11.0
3         AAA             2013J     28400.0  546714.0 -10.0        1.0
4         AAA             2013J     28400.0  546652.0 -10.0        8.0

  student_id_general id_site_general    source guid_student_id guid_site_id  \
0              28400          546652  original             NaN          NaN
1              28400          546652  original             NaN          NaN
2              28400          546614  original             NaN          NaN
3              28400          546714  original             NaN          NaN
4              28400          546652  original             NaN          NaN

  type_assign week_from weel_to disability modulo  week1  week2  days  \
0         NaN       NaN     NaN        NaN    NaN    NaN    NaN   NaN
1         NaN       NaN     NaN        NaN    NaN    NaN    NaN   NaN
2         NaN       NaN     NaN        NaN    NaN    NaN    NaN   NaN
3         NaN       NaN     NaN        NaN    NaN    NaN    NaN   NaN
4         NaN       NaN     NaN        NaN    NaN    NaN    NaN   NaN

  presentation
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
    id_site code_module code_presentation activity_type  week_from  week_to  \
0  546943.0         AAA             2013J      resource        NaN      NaN
1  546712.0         AAA             2013J     oucontent        NaN      NaN
2  546998.0         AAA             2013J      resource        NaN      NaN
3  546888.0         AAA             2013J           url        NaN      NaN
4  547035.0         AAA             2013J      resource        NaN      NaN

  id_site_general    source guid_site_id
0          546943  original          NaN
1          546712  original          NaN
2          546998  original          NaN
3          546888  original          NaN
4          547035  original          NaN

In [21]:

# Porcentaje de missing values
print("Assessment\n",(df_assessment_combined.isnull().mean() * 100).round(2))
print("\n")
print("Courses\n",(Courses_combined.isnull().mean() * 100).round(2))
print("\n")
print("Registration\n",(Registration_combined.isnull().mean() * 100).round(2))
print("\n")
print("Student Assessment\n",(StudentAssessment_combined.isnull().mean() * 100).round(2))
print("\n")
print("Student Info\n",(StudentInfo_combined.isnull().mean() * 100).round(2))
print("\n")
print("Student Vle\n",(StudentVle_combined.isnull().mean() * 100).round(2))
print("\n")
print("Vle\n",(vle_combined.isnull().mean() * 100).round(2))

Assessment
 code_module               0.00
code_presentation         0.00
id_assessment            11.97
assessment_type           0.00
date                     16.67
weight                    0.00
id_assessment_general     0.00
source                    0.00
guid_assess_id           88.03
days                     88.03
dtype: float64


Courses
 code_module                   0.0
code_presentation             0.0
module_presentation_length    0.0
source                        0.0
dtype: float64


Registration
 code_module             0.00
code_presentation       0.00
id_student              0.45
date_registration       0.14
date_unregistration    69.24
student_id_general      0.00
source                  0.00
guid_studente_id       99.55
dtype: float64


Student Assessment
 id_assessment              0.47
id_student                 0.47
date_submitted             0.00
is_banked                  0.00
score                      0.10
student_id_general         0.00
id_assessment_general      0.00
source                     0.00
guid_student_id           99.53
guid_assess_id            99.53
assessment_type           99.53
date                      99.53
weight                    99.53
gender                    99.53
region                   100.00
highest_education         99.53
imd_band                  99.53
age_band                  99.53
num_of_prev_attempts      99.53
studied_credits           99.53
disability                99.53
final_result              99.53
status                    99.53
module                    99.53
presentation              99.53
date_real_days            99.53
id_assetcode              99.53
dtype: float64


Student Info
 code_module              0.00
code_presentation        0.00
id_student               0.45
gender                   0.00
region                   0.00
highest_education        0.00
imd_band                 3.45
age_band                 0.05
num_of_prev_attempts     0.05
studied_credits          0.05
disability               0.00
final_result             0.00
student_id_general       0.00
source                   0.00
guid_student_id         99.55
dtype: float64


Student Vle
 code_module            0.13
code_presentation      0.13
id_student             0.13
id_site                0.13
date                   0.00
sum_click              0.00
student_id_general     0.00
id_site_general        0.00
source                 0.00
guid_student_id       99.87
guid_site_id          99.87
type_assign           99.87
week_from             99.87
weel_to               99.87
disability            99.87
modulo                99.87
week1                 99.87
week2                 99.87
days                  99.87
presentation          99.87
dtype: float64


Vle
 id_site               0.89
code_module           0.00
code_presentation     0.00
activity_type         0.00
week_from            81.65
week_to              81.65
id_site_general       0.00
source                0.00
guid_site_id         99.11
dtype: float64

In [22]:
# Eliminar columnas con >80% missing que no aportan

cols_to_drop_assessment = ['guid_assess_id', 'days']
cols_to_drop_student_assessment = [
    'guid_student_id', 'guid_assess_id', 'assessment_type', 'date', 'weight', 'gender', 'region',
    'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits',
    'disability', 'final_result', 'status', 'module', 'presentation', 'date_real_days', 'id_assetcode'
]
cols_to_drop_student_vle = [
    'guid_student_id', 'guid_site_id', 'type_assign', 'week_from', 'weel_to',
    'disability', 'modulo', 'week1', 'week2', 'days', 'presentation'
]
cols_to_drop_vle = ['guid_site_id', 'week_from', 'week_to']

# Drop
df_assessment_combined.drop(columns=cols_to_drop_assessment, inplace=True, errors='ignore')
StudentAssessment_combined.drop(columns=cols_to_drop_student_assessment, inplace=True, errors='ignore')
StudentVle_combined.drop(columns=cols_to_drop_student_vle, inplace=True, errors='ignore')
vle_combined.drop(columns=cols_to_drop_vle, inplace=True, errors='ignore')

“Se eliminaron columnas con >80% de valores nulos y sin valor predictivo directo o sin correspondencia con otras tablas, para reducir ruido en el dataset.”

In [23]:
# Completar valores

Registration_combined['date_unregistration'] = Registration_combined['date_unregistration'].fillna(9999)
StudentInfo_combined['imd_band'] = StudentInfo_combined['imd_band'].fillna('Unknown')
StudentInfo_combined['age_band'] = StudentInfo_combined['age_band'].fillna(StudentInfo_combined['age_band'].mode()[0])
StudentInfo_combined['num_of_prev_attempts'] = StudentInfo_combined['num_of_prev_attempts'].fillna(StudentInfo_combined['num_of_prev_attempts'].median())
StudentInfo_combined['studied_credits'] = StudentInfo_combined['studied_credits'].fillna(StudentInfo_combined['studied_credits'].median())
df_assessment_combined['date'] = df_assessment_combined['date'].fillna(df_assessment_combined['date'].median())
StudentAssessment_combined = StudentAssessment_combined.dropna(subset=['id_assessment', 'id_student'])

In [24]:
# Mostrar categorías únicas para definir el orden real
print("age_band:", StudentInfo_combined['age_band'].unique())
print("highest_education:", StudentInfo_combined['highest_education'].unique())
print("imd_band:", StudentInfo_combined['imd_band'].unique())

age_band: ['55<=' '35-55' '0-35' '18-20' ' > 35' '20-25' '25-30' '30-35']
highest_education: ['HE Qualification' 'A Level or Equivalent' 'Lower Than A Level'
 'Post Graduate Qualification' 'No Formal quals']
imd_band: ['90-100%' '20-30%' '30-40%' '50-60%' '80-90%' '70-80%' 'Unknown' '60-70%'
 '40-50%' '10-20' '0-10%']

In [25]:
StudentInfo_combined['age_band'] = pd.Categorical(
    StudentInfo_combined['age_band'],
    categories=['0-35', '35-55', '55<='],
    ordered=True
)

StudentInfo_combined['highest_education'] = pd.Categorical(
    StudentInfo_combined['highest_education'],
    categories=[
        'No Formal quals',
        'Lower Than A Level',
        'A Level or Equivalent',
        'HE Qualification',
        'Post Graduate Qualification'
    ],
    ordered=True
)

StudentInfo_combined['imd_band'] = pd.Categorical(
    StudentInfo_combined['imd_band'],
    categories=[
        '0-10%',
        '10-20%',
        '20-30%',
        '30-40%',
        '40-50%'
    ],
    ordered=True
)

In [26]:
# Verificar datos limpios

print(StudentInfo_combined.isnull().mean() * 100)
print(df_assessment_combined.isnull().mean() * 100)
print(Registration_combined.isnull().mean() * 100)
print(StudentAssessment_combined.isnull().mean() * 100)
print(StudentVle_combined.isnull().mean() * 100)
print(vle_combined.isnull().mean() * 100)

code_module              0.000000
code_presentation        0.000000
id_student               0.452033
gender                   0.000000
region                   0.000000
highest_education        0.000000
imd_band                57.631105
age_band                 0.397056
num_of_prev_attempts     0.000000
studied_credits          0.000000
disability               0.000000
final_result             0.000000
student_id_general       0.000000
source                   0.000000
guid_student_id         99.547967
dtype: float64
code_module               0.000000
code_presentation         0.000000
id_assessment            11.965812
assessment_type           0.000000
date                      0.000000
weight                    0.000000
id_assessment_general     0.000000
source                    0.000000
dtype: float64
code_module             0.000000
code_presentation       0.000000
id_student              0.452033
date_registration       0.137442
date_unregistration     0.000000
student_id_general      0.000000
source                  0.000000
guid_studente_id       99.547967
dtype: float64
id_assessment            0.000000
id_student               0.000000
date_submitted           0.000000
is_banked                0.000000
score                    0.099476
student_id_general       0.000000
id_assessment_general    0.000000
source                   0.000000
dtype: float64
code_module           0.130176
code_presentation     0.130176
id_student            0.130176
id_site               0.130176
date                  0.000033
sum_click             0.000033
student_id_general    0.000000
id_site_general       0.000000
source                0.000000
dtype: float64
id_site              0.887712
code_module          0.000000
code_presentation    0.000000
activity_type        0.000000
id_site_general      0.000000
source               0.000000
dtype: float64

In [27]:
# Verificar datos limpios

print(StudentInfo_combined.isnull().mean() * 100)
print(df_assessment_combined.isnull().mean() * 100)
print(Registration_combined.isnull().mean() * 100)
print(StudentAssessment_combined.isnull().mean() * 100)
print(StudentVle_combined.isnull().mean() * 100)
print(vle_combined.isnull().mean() * 100)

code_module              0.000000
code_presentation        0.000000
id_student               0.452033
gender                   0.000000
region                   0.000000
highest_education        0.000000
imd_band                57.631105
age_band                 0.397056
num_of_prev_attempts     0.000000
studied_credits          0.000000
disability               0.000000
final_result             0.000000
student_id_general       0.000000
source                   0.000000
guid_student_id         99.547967
dtype: float64
code_module               0.000000
code_presentation         0.000000
id_assessment            11.965812
assessment_type           0.000000
date                      0.000000
weight                    0.000000
id_assessment_general     0.000000
source                    0.000000
dtype: float64
code_module             0.000000
code_presentation       0.000000
id_student              0.452033
date_registration       0.137442
date_unregistration     0.000000
student_id_general      0.000000
source                  0.000000
guid_studente_id       99.547967
dtype: float64
id_assessment            0.000000
id_student               0.000000
date_submitted           0.000000
is_banked                0.000000
score                    0.099476
student_id_general       0.000000
id_assessment_general    0.000000
source                   0.000000
dtype: float64
code_module           0.130176
code_presentation     0.130176
id_student            0.130176
id_site               0.130176
date                  0.000033
sum_click             0.000033
student_id_general    0.000000
id_site_general       0.000000
source                0.000000
dtype: float64
id_site              0.887712
code_module          0.000000
code_presentation    0.000000
activity_type        0.000000
id_site_general      0.000000
source               0.000000
dtype: float64

In [28]:
StudentInfo_combined.drop(columns=['guid_student_id'], inplace=True)
df_assessment_combined.drop(columns=['id_assessment'], inplace=True)
Registration_combined.drop(columns=['guid_studente_id'], inplace=True)
vle_combined.drop(columns=['id_site'], inplace=True)

In [29]:
print(StudentInfo_combined.shape)
print(Registration_combined.shape)
print(StudentVle_combined.shape)
print(StudentAssessment_combined.shape)

(32741, 14)
(32741, 7)
(3034351, 9)
(173912, 8)

In [30]:
student_vle_agg = StudentVle_combined.groupby(
    ['id_student', 'code_module', 'code_presentation']
).agg(
    sum_click_total=('sum_click', 'sum'),
    count_vle_days=('date', 'nunique')
).reset_index()

In [31]:
student_assess_agg = StudentAssessment_combined.groupby('id_student').agg(
    mean_score=('score', 'mean'),
    num_assessments=('id_assessment_general', 'nunique')
).reset_index()

In [34]:
df_main = StudentInfo_combined.merge(
    Registration_combined,
    on=['id_student', 'code_module', 'code_presentation'],
    how='left',
    suffixes=('_info', '_reg')
)

# Merge with StudentAssessment_combined first
df_main = df_main.merge(
    StudentAssessment_combined,
    on='id_student',
    how='left'
)

# Then merge with df_assessment_combined
df_main = df_main.merge(
    df_assessment_combined.drop_duplicates(subset=['id_assessment_general']),
    on='id_assessment_general',
    how='left'
)

# Finally merge with aggregated student_vle_agg
df_main = df_main.merge(
    student_vle_agg,
    left_on=['id_student', 'code_module_x', 'code_presentation_x'],
    right_on=['id_student', 'code_module', 'code_presentation'],
    how='left'
)

In [35]:
df_main.to_csv('OULADX.csv', index=False)